[tool.poetry]
name = "monopoly-probabilities"
version = "0.2.0"
description = "Calculate the probabilties of landing on each different square on a monopoly board."
authors = ["George Waters <george@georgeh2os.com>"]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
cython = {version = "^0.29.15", optional = true}
pyinstaller = {version = "^5.0", optional = true}
pyoxidizer = {version = "^0.22.0", optional = true}
Nuitka = {version = "^1.0", optional = true}
zstandard = {version = "^0.18.0", optional = true}
ordered-set = {version = "^4.1.0", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
cython = ["cython"]
pyinstaller = ["pyinstaller"]
pyoxidizer = ["pyoxidizer"]
Nuitka = ["Nuitka", "zstandard", "ordered-set"]

[tool.poetry.scripts]
monopoly = "app:main"
scriptopoly = "script:main"

[build-system]
requires = ["setuptools>=59.0.1"]
build-backend = "setuptools.build_meta"
