[tool.poetry]
name = "monopoly-probabilities"
version = "0.1.0"
description = "Calculate the probabilties of landing on each different square on a monopoly board."
authors = ["George Waters <george@georgeh2os.com>"]
packages = [
    { include = "monopoly" }
]
build = "build.py"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
cython = {version = "^0.29.15", optional = true}
pyinstaller = {version = "^4.8", optional = true}
pyoxidizer = {version = "^0.18.0", optional = true}
Nuitka = {version = "^0.6.19", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
cython = ["cython"]
pyinstaller = ["pyinstaller"]
pyoxidizer = ["pyoxidizer"]
Nuitka = ["Nuitka"]

[tool.poetry.scripts]
monopoly = "monopoly:main"
monopolize = "build:cythonize_monopoly"

[build-system]
requires = ["poetry>=0.12", "setuptools>=59.0.1"]
build-backend = "poetry.masonry.api"
