name: Build and Deploy Github Pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  gh_pages:
    name: Build & Deploy Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Deploy
        uses: dunkmann00/jekyll-v4-gh-pages@v1
