name: Build Release Binaries

on:
  release:
    types: [published]


jobs:
  build:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    env:
      NO_VIRTUAL_ENV: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-2022, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Monopoly
        run: python install_monopoly.py
      - name: Install Binary Build Requirements
        run: scriptopoly install
      - name: Build All Binaries
        run: scriptopoly all-binaries
      - name: Create tar.gz from dist folder
        if: runner.os != 'Windows'
        run: tar cvzf dist/monopoly-${{ matrix.os }}-${{ runner.arch }}.tar.gz dist/*
      - name: Create zip from dist folder
        if: runner.os == 'Windows'
        run: 7z a -tzip dist\monopoly-${{ matrix.os }}-${{ runner.arch }}.zip dist\*
      - name: Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: |
            dist/monopoly-${{ matrix.os }}-${{ runner.arch }}.tar.gz
            dist\monopoly-${{ matrix.os }}-${{ runner.arch }}.zip
