name: Build Release Binaries

on:
  release:
    types: [published]


jobs:
  build:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    env:
      NO_VIRTUAL_ENV: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-2022, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Monopoly
        run: python install_monopoly.py
      - name: Install Binary Build Requirements
        run: scriptopoly install
      - name: Set BUILD_DISTPATH Environment Variable
        run: echo "BUILD_DISTPATH=monopoly-$(${{ github.ref }})-$(python -c "import platform; print(platform.platform())")" >> ${{ github.env }}
      - name: Build All Binaries
        run: scriptopoly all-binaries
      - name: Create Build Archive
        run: scriptopoly archive-binaries
      - name: Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: ${{ env.BUILD_DISTPATH }}.*
